/* ================================================
   MERI DUKAAN v8.0 — SERVICE WORKER
   Generated by Workbox CLI. Do not edit manually.
   Run: npm run sw  to regenerate after changes.
   ================================================ */
importScripts('https://storage.googleapis.com/workbox-cdn/releases/7.3.0/workbox-sw.js');

const { precacheAndRoute, cleanupOutdatedCaches } = workbox.precaching;
const { registerRoute }                           = workbox.routing;
const { StaleWhileRevalidate, CacheFirst,
        NetworkFirst }                            = workbox.strategies;
const { ExpirationPlugin }                        = workbox.expiration;
const { BackgroundSyncPlugin }                    = workbox.backgroundSync;

// ── Cleanup old caches on activate ──────────────────────────────────────
cleanupOutdatedCaches();

// ── Precache app shell (auto-injected by Workbox CLI) ───────────────────
precacheAndRoute(self.__WB_MANIFEST || []);

// ── Google Fonts — CacheFirst 365 days ──────────────────────────────────
registerRoute(
  ({ url }) => url.origin === 'https://fonts.googleapis.com' ||
               url.origin === 'https://fonts.gstatic.com',
  new CacheFirst({
    cacheName: 'md-fonts-v8',
    plugins: [new ExpirationPlugin({ maxEntries: 20, maxAgeSeconds: 31_536_000 })]
  })
);

// ── CDN assets (Chart.js, jsPDF, Tabler Icons) — StaleWhileRevalidate ───
registerRoute(
  ({ url }) => url.origin === 'https://cdnjs.cloudflare.com' ||
               url.origin === 'https://cdn.jsdelivr.net'      ||
               url.hostname.includes('gstatic.com'),
  new StaleWhileRevalidate({
    cacheName: 'md-cdn-v8',
    plugins: [new ExpirationPlugin({ maxEntries: 40, maxAgeSeconds: 604_800 })]
  })
);

// ── Firebase JS SDK — NetworkFirst (must stay fresh) ────────────────────
registerRoute(
  ({ url }) => url.hostname.includes('firebase') ||
               url.hostname.includes('googleapis.com'),
  new NetworkFirst({ networkTimeoutSeconds: 5, cacheName: 'md-firebase-v8' })
);

// ── Navigation (SPA routing) — return cached index.html ─────────────────
registerRoute(
  ({ request }) => request.mode === 'navigate',
  new NetworkFirst({
    cacheName: 'md-nav-v8',
    plugins: [new ExpirationPlugin({ maxEntries: 5 })]
  })
);

// ── Background Sync for queued writes ────────────────────────────────────
const bgSync = new BackgroundSyncPlugin('md-write-queue', {
  maxRetentionTime: 24 * 60 // 24 hours
});

// ── SKIP WAITING on postMessage ──────────────────────────────────────────
self.addEventListener('message', (e) => {
  if (e.data?.type === 'SKIP_WAITING') self.skipWaiting();
});

// ── Push notification display ─────────────────────────────────────────────
self.addEventListener('push', (e) => {
  const data = e.data?.json() || {};
  const { title = 'Meri Dukaan', body = 'New update', icon = './icons/icon-192.png', url = './' } = data;
  e.waitUntil(self.registration.showNotification(title, {
    body, icon, badge: './icons/icon-maskable-192.png',
    data: { url },
    vibrate: [100, 50, 100],
    actions: [{ action: 'open', title: 'Open' }, { action: 'close', title: 'Dismiss' }]
  }));
});

self.addEventListener('notificationclick', (e) => {
  e.notification.close();
  if (e.action === 'close') return;
  e.waitUntil(clients.openWindow(e.notification.data?.url || './'));
});
